theme = "onedarker"

[editor]
line-number = "absolute"
mouse = false
bufferline = "multiple"
color-modes = true
cursorline = true
auto-pairs = true
auto-completion = true
auto-format = true
completion-trigger-len = 1
preview-completion-insert = false
completion-replace = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["workspace-diagnostics"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 10

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
characters = { space = "·", nbsp = "⍽", tab = "→", newline = "⏎" }

[editor.indent-guides]
character = "|"
render = true

[keys.normal]
# Quick access to commonly used commands
space.f = "file_picker"
space.b = "buffer_picker"
space.s = "symbol_picker"
space.g = "goto_definition"
space.r = "rename_symbol"
space.a = "code_action"
space.d = "diagnostics_picker"
space.h = "hover"

# Custom commands for NixOS development
space.n.b = ":sh build-host"
space.n.h = ":sh build-home"
space.n.t = ":sh test"
space.n.f = ":sh fmt"
space.n.l = ":sh lint"
space.n.v = ":sh vm"
