[language-server.nixd]
command = "nixd"

[language-server.taplo]
command = "taplo"
config = { taplo = { formatting = { command = "taplo fmt" } } }

[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
comment-token = "#"
# language-servers = ["nixd", "nil"]
language-servers = ["nixd"]
auto-format = true
formatter = { command = "nixfmt" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]
auto-format = true

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true
